name: Build and test

on:
  # push:
  #   branches:
  #     - master
  #     - "release/v[0-9].[0-9].[0-9]"
  pull_request:
    types:
      - opened # triggers build when opened
      - synchronize # triggers build when commits are pushed to HEAD
    branches:
      #- master
      #- "release/v[0-9].[0-9].[0-9]"
      - "feature/**"
  # Manual trigger
  workflow_dispatch:

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          #- macos-13-xlarge
        build_type:
          - Release
          - Debug
          #- DebugWithRelInfo

    uses: Deltares/MeshKernel/.github/workflows/build-and-test-workflow.yml@feature/GRIDEDIT-892_reusable_build_and_test_workflow
    with:
       platform: ${{ matrix.platform }}
       build_type: ${{ matrix.build_type }}