name: Build and test

on:
  pull_request:
    types:
      - opened # triggers build when opened
      - synchronize # triggers build when commits are pushed to HEAD
    branches:
      - "feature/**"
  # Manual trigger
  workflow_dispatch:

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        target_platform:
          - ubuntu-latest
          - macos-latest
        build_type:
          - Release
          - Debug

    #uses: Deltares/MeshKernel/.github/workflows/build-and-test-workflow.yml@13b53c2b5f6c25c277d753dbca553fabf4d31bbe
    uses: ./.github/workflows/build-and-test-workflow.yml
    with:
      target_platform: ${{ matrix.target_platform }}
      build_type: ${{ matrix.build_type }}
